image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

stages:
  - test
  - build

test:crawler:
  stage: test
  script:
    - cd src/crawler
    - pip install -r requirements.txt -r requirements-test.txt
    - coverage run -m unittest discover -s ./tests/
    - coverage report ./crawler/*.py

test:ui:
  stage: test
  script:
    - cd src/ui
    - pip install -r requirements.txt -r requirements-test.txt
    - coverage run -m unittest discover -s ./tests/
    - coverage report ./ui/*.py

build:
  stage: build
  services:
    - docker
  before_script:
    - docker -v
    - docker-compose -v
    - echo "login to docker.io via env variable"
  script:
    - cd docker
    - docker-compose -f docker-compose.yml config
